--- #YAML:1.0
name:               IO-Interactive
version:            0.0.5
abstract:           Utilities for interactive I/O
author:
    - Damian Conway <DCONWAY@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
    version:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
