--- #YAML:1.0
name:                IO-Interactive
version:             0.0.3_01
abstract:            Utilities for interactive I/O
license:             perl
author:              
    - Damian Conway <DCONWAY@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
